# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\Python\Cal.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Cal(object):
    def setupUi(self, Cal):
        Cal.setObjectName("Cal")
        Cal.setEnabled(True)
        Cal.resize(573, 744)
        Cal.setLayoutDirection(QtCore.Qt.RightToLeft)
        Cal.setAutoFillBackground(False)
        Cal.setStyleSheet("#Form{\n"
"    background:#202020;\n"
"\n"
"}\n"
"\n"
"QPushButton{\n"
"    background:#d2d3d7;\n"
"    border:none;\n"
"    font-family: Arial, Helvetica, sans-serif;\n"
"    font-size:30px;\n"
"    color:#202020;\n"
"}\n"
"\n"
"QLineEdit{\n"
"    background:#202020;\n"
"    border:none;\n"
"    font-family: Arial, Helvetica, sans-serif;\n"
"    font-size:120px;\n"
"    color:white;\n"
"}\n"
"QLabel{\n"
"     background:#ffffff;\n"
"    border:none;\n"
"    font-family: Arial, Helvetica, sans-serif;\n"
"    font-size:60px;\n"
"    color:black;\n"
"}")
        self.pushButton7 = QtWidgets.QPushButton(Cal, clicked= lambda: self.press_it("7"))
        self.pushButton7.setGeometry(QtCore.QRect(60, 190, 81, 81))
        self.pushButton7.setObjectName("pushButton7")
        self.pushButton8 = QtWidgets.QPushButton(Cal, clicked= lambda: self.press_it("8"))
        self.pushButton8.setGeometry(QtCore.QRect(180, 190, 81, 81))
        self.pushButton8.setObjectName("pushButton8")
        self.pushButton9 = QtWidgets.QPushButton(Cal, clicked= lambda: self.press_it("9"))
        self.pushButton9.setGeometry(QtCore.QRect(300, 190, 81, 81))
        self.pushButton9.setObjectName("pushButton9")
        self.pushButtondiv = QtWidgets.QPushButton(Cal, clicked= lambda: self.press_it("%"))
        self.pushButtondiv.setGeometry(QtCore.QRect(420, 190, 81, 81))
        self.pushButtondiv.setObjectName("pushButtondiv")
        self.pushButton4 = QtWidgets.QPushButton(Cal, clicked= lambda: self.press_it("4"))
        self.pushButton4.setGeometry(QtCore.QRect(60, 300, 81, 81))
        self.pushButton4.setObjectName("pushButton4")
        self.pushButtonmul = QtWidgets.QPushButton(Cal, clicked= lambda: self.press_it("*"))
        self.pushButtonmul.setGeometry(QtCore.QRect(420, 300, 81, 81))
        self.pushButtonmul.setObjectName("pushButtonmul")
        self.pushButton6 = QtWidgets.QPushButton(Cal, clicked= lambda: self.press_it("6"))
        self.pushButton6.setGeometry(QtCore.QRect(300, 300, 81, 81))
        self.pushButton6.setObjectName("pushButton6")
        self.pushButton5 = QtWidgets.QPushButton(Cal, clicked= lambda: self.press_it("5"))
        self.pushButton5.setGeometry(QtCore.QRect(180, 300, 81, 81))
        self.pushButton5.setObjectName("pushButton5")
        self.pushButton3 = QtWidgets.QPushButton(Cal, clicked= lambda: self.press_it("3"))
        self.pushButton3.setGeometry(QtCore.QRect(300, 410, 81, 81))
        self.pushButton3.setObjectName("pushButton3")
        self.pushButton2 = QtWidgets.QPushButton(Cal, clicked= lambda: self.press_it("2"))
        self.pushButton2.setGeometry(QtCore.QRect(180, 410, 81, 81))
        self.pushButton2.setObjectName("pushButton2")
        self.pushButton1 = QtWidgets.QPushButton(Cal, clicked= lambda: self.press_it("1"))
        self.pushButton1.setGeometry(QtCore.QRect(60, 410, 81, 81))
        self.pushButton1.setObjectName("pushButton1")
        self.pushButtonminus = QtWidgets.QPushButton(Cal, clicked= lambda: self.press_it("-"))
        self.pushButtonminus.setGeometry(QtCore.QRect(420, 410, 81, 81))
        self.pushButtonminus.setObjectName("pushButtonminus")
        self.pushButtonequal = QtWidgets.QPushButton(Cal, clicked= lambda: self.press_it("="))
        self.pushButtonequal.setGeometry(QtCore.QRect(60, 520, 81, 81))
        self.pushButtonequal.setObjectName("pushButtonequal")
        self.pushButton0 = QtWidgets.QPushButton(Cal, clicked= lambda: self.press_it("0"))
        self.pushButton0.setGeometry(QtCore.QRect(180, 520, 81, 81))
        self.pushButton0.setObjectName("pushButton0")
        self.pushButtondeci = QtWidgets.QPushButton(Cal, clicked= lambda: self.press_it("."))
        self.pushButtondeci.setGeometry(QtCore.QRect(300, 520, 81, 81))
        self.pushButtondeci.setObjectName("pushButtondeci")
        self.pushButtonplus = QtWidgets.QPushButton(Cal, clicked= lambda: self.press_it("+"))
        self.pushButtonplus.setGeometry(QtCore.QRect(420, 520, 81, 81))
        self.pushButtonplus.setObjectName("pushButtonplus")
        self.pushButtonCE = QtWidgets.QPushButton(Cal, clicked= lambda: self.press_it("CE"))
        self.pushButtonCE.setGeometry(QtCore.QRect(60, 630, 201, 71))
        self.pushButtonCE.setObjectName("pushButtonCE")
        self.pushButtonC = QtWidgets.QPushButton(Cal, clicked= lambda: self.press_it("C"))
        self.pushButtonC.setGeometry(QtCore.QRect(300, 630, 201, 71))
        self.pushButtonC.setObjectName("pushButtonC")
        self.label = QtWidgets.QLabel(Cal)
        self.label.setGeometry(QtCore.QRect(60, 40, 441, 121))
        self.label.setToolTipDuration(0)
        self.label.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.label.setAlignment(QtCore.Qt.AlignRight)
        self.label.setObjectName("label")
        self.lineEdit = QtWidgets.QLineEdit(Cal)
        self.lineEdit.setGeometry(QtCore.QRect(40, 20, 481, 701))
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit.raise_()
        self.pushButton7.raise_()
        self.pushButton8.raise_()
        self.pushButton9.raise_()
        self.pushButtondiv.raise_()
        self.pushButton4.raise_()
        self.pushButtonmul.raise_()
        self.pushButton6.raise_()
        self.pushButton5.raise_()
        self.pushButton3.raise_()
        self.pushButton2.raise_()
        self.pushButton1.raise_()
        self.pushButtonminus.raise_()
        self.pushButtonequal.raise_()
        self.pushButton0.raise_()
        self.pushButtondeci.raise_()
        self.pushButtonplus.raise_()
        self.pushButtonCE.raise_()
        self.pushButtonC.raise_()
        self.label.raise_()

        self.retranslateUi(Cal)
        QtCore.QMetaObject.connectSlotsByName(Cal)

    def press_it(self, pressed):
        if pressed == "C":
            self.label.setText("0")
        else:
            #check to see if start 0 and delete 0
            if self.label.text() == "0":
                self.label.setText("")
            # Concatenate the pressed button with what was there already
            self.label.setText(f'{self.label.text()}{pressed}')

    def retranslateUi(self, Cal):
        _translate = QtCore.QCoreApplication.translate
        Cal.setWindowTitle(_translate("Cal", "Form"))
        self.pushButton7.setText(_translate("Cal", "7"))
        self.pushButton8.setText(_translate("Cal", "8"))
        self.pushButton9.setText(_translate("Cal", "9"))
        self.pushButtondiv.setText(_translate("Cal", "/"))
        self.pushButton4.setText(_translate("Cal", "4"))
        self.pushButtonmul.setText(_translate("Cal", "X"))
        self.pushButton6.setText(_translate("Cal", "6"))
        self.pushButton5.setText(_translate("Cal", "5"))
        self.pushButton3.setText(_translate("Cal", "3"))
        self.pushButton2.setText(_translate("Cal", "2"))
        self.pushButton1.setText(_translate("Cal", "1"))
        self.pushButtonminus.setText(_translate("Cal", "-"))
        self.pushButtonequal.setText(_translate("Cal", "="))
        self.pushButton0.setText(_translate("Cal", "0"))
        self.pushButtondeci.setText(_translate("Cal", "."))
        self.pushButtonplus.setText(_translate("Cal", "+"))
        self.pushButtonCE.setText(_translate("Cal", "CE"))
        self.pushButtonC.setText(_translate("Cal", "C"))
        self.label.setText(_translate("Cal", "0"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Cal = QtWidgets.QWidget()
    ui = Ui_Cal()
    ui.setupUi(Cal)
    Cal.show()
    sys.exit(app.exec_())
