# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MENU.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(721, 420)
        Form.setStyleSheet("background-image: url(:/choose/BLACK.jpg);")
        self.CONNECTButton = QtWidgets.QPushButton(Form)
        self.CONNECTButton.setGeometry(QtCore.QRect(400, 190, 271, 151))
        self.CONNECTButton.setStyleSheet("background-image: url(:/WHITE/WHITE.jpg);\n"
"font: 28pt \"OCR A Extended\";")
        self.CONNECTButton.setObjectName("CONNECTButton")
        self.DINOButton = QtWidgets.QPushButton(Form)
        self.DINOButton.setGeometry(QtCore.QRect(60, 190, 271, 151))
        self.DINOButton.setStyleSheet("background-image: url(:/WHITE/WHITE.jpg);\n"
"font: 28pt \"OCR A Extended\";")
        self.DINOButton.setObjectName("DINOButton")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(100, 80, 531, 91))
        self.label.setStyleSheet("\n"
"font: 36pt \"Sylfaen\";\n"
"color: rgb(0, 25, 255);")
        self.label.setObjectName("label")
        self.widget = QtWidgets.QWidget(Form)
        self.widget.setGeometry(QtCore.QRect(0, 0, 741, 91))
        self.widget.setStyleSheet("background-image: url(:/DINO/DinoJump.png);")
        self.widget.setObjectName("widget")
        self.widget_2 = QtWidgets.QWidget(Form)
        self.widget_2.setGeometry(QtCore.QRect(10, 340, 101, 80))
        self.widget_2.setStyleSheet("background-image: url(:/DINO/LargeCactus3.png);")
        self.widget_2.setObjectName("widget_2")
        self.widget_3 = QtWidgets.QWidget(Form)
        self.widget_3.setGeometry(QtCore.QRect(580, 350, 101, 80))
        self.widget_3.setStyleSheet("background-image: url(:/DINO/LargeCactus2.png);")
        self.widget_3.setObjectName("widget_3")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.CONNECTButton.setText(_translate("Form", "CONNECT 4"))
        self.DINOButton.setText(_translate("Form", "DINO GAME"))
        self.label.setText(_translate("Form", "Please Choose Your Game"))
import back1_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
